version: "3.7"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"
  config-service:
    image: lms/config-service:1.1-SNAPSHOT
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/enrollment/docker  || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
  discovery-service:
    image: lms/discovery-service:1.1-SNAPSHOT
    ports:
      - "8061:8061"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    healthcheck:
      test: curl --fail http://localhost:8061/eureka/v2/apps || exit 1
      interval: 4s
      timeout: 2s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: docker
  adminTask-service:
    image: lms/admin-service:1.2-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  content-service:
    image: lms/content-service:1.2-SNAPSHOT
    ports:
      - "8080"
    depends_on:
        discovery-service:
            condition: service_healthy
    links:
        - config-service
        - discovery-service
        - zipkin
        - adminTask-service
    environment:
        SPRING_PROFILES_ACTIVE: docker
  course-service:
    image: lms/course-service:1.2-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - zipkin
      - adminTask-service
      - content-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  email-service:
    image: lms/email-service:1.2-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - zipkin
      - adminTask-service
      - content-service
      - course-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  enrollment-service:
    image: lms/enrollment-service:1.2-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - zipkin
      - adminTask-service
      - content-service
      - course-service
      - email-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  learner-service:
    image: lms/learner-service:1.2-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - zipkin
      - adminTask-service
      - content-service
      - course-service
      - email-service
      - enrollment-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  order-service:
    image: lms/order-service:1.2-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - zipkin
      - adminTask-service
      - content-service
      - course-service
      - email-service
      - enrollment-service
      - learner-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  payment-service:
    image: lms/payment-service:1.2-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - zipkin
      - adminTask-service
      - content-service
      - course-service
      - email-service
      - enrollment-service
      - learner-service
      - order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  user-service:
    image: lms/user-service:1.2-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - zipkin
      - adminTask-service
      - content-service
      - course-service
      - email-service
      - enrollment-service
      - learner-service
      - order-service
      - payment-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  gateway-service:
    image: lms/gateway-service:1.1-SNAPSHOT
    ports:
      - "8060:8060"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - config-service
      - discovery-service
      - adminTask-service
      - content-service
      - course-service
      - email-service
      - enrollment-service
      - learner-service
      - order-service
      - payment-service
      - user-service
      - zipkin