springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true

spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8088"
  banner:
    location: banner.txt