
spring:
  application:
    name: course-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: 
      database: course-service

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html

---
#####Local
spring:
  application:
    name: course-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      uri: 
      database: course-service
#  data:
#    mongodb:
#      uri: mongodb://root:root@localhost:27017/course-service?authSource=admin



#
#spring.data.mongodb.uri=mongodb+srv://Sandun2001:Sandun2001@cluster0.r33qmfk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=course-service
