spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: course-service
    banner:
      location: banner.txt
  config:
    import: "optional:configserver:http://localhost:8088"

#server.port=7012
#spring.banner.location=banner.txt
#
#spring.data.mongodb.uri=mongodb+srv://Sandun2001:Sandun2001@cluster0.r33qmfk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=course-service