#Common configuration for all profiles
# Stripe configuration
stripe:
  api:
    publicKey: pk_test_51PAG7VSEMTakDOaEfnDW1jukOAvF2rqhrvZyA8xjI3A6zboQmcY8xCNrVLfRD1niDrGihvQ2MnRQTgYS8kympJ5t00HZwWR4fT
    secretKey: sk_test_51PAG7VSEMTakDOaEXo7CML93QLTxSK1OpkjxHv1qXEAdyFYUWO37D1VDxBKcF8xqDqhq9FgufCHwkHDp3H2Jbbll00ZAtxBfIC


springdoc:
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  application:
      name: payment-service
  banner:
      location: banner.txt
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name:  payment-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://localhost:8088"



