# Common configuration for all profiles
spring:
  application:
    name: enrollment-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enrollment_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cloudinary:
  cloud_name: dfbqv9hqr
  api_key: 234434566613793
  api_secret: nlf8S2sJO36I6RIqsY15D1CUAG0

# Docker-specific configuration
---
spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-Enrollment:3307/enrollment_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none


# Local development configuration
---
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3305/enrollment_service
#    username: root
#    password: root
