# Common configuration for all profiles
spring:
  application:
    name: user-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/user_service?allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 937264332283-k2jkgnctiipbvqc7b566ab506kct7lp2.apps.googleusercontent.com
            clientSecret: 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
application:
  security:
    jwt:
      secret-key: QDozrk7CUofsDF1GY0NLVWY/B7lH+A9xoQ9ztn+XhRBa486xwK2ePhFxJesPVYX4UIicILdrjnH479zlt94+3TDJW7081lrfbNQYENzNq0epSHpTdtlqzntf4XONivFeRhAGslX5tnkgPOl1q3UQ5l15YNPapqg7iB6v6lySewI4BI47ncIjYcSAHl2+Rdt+wrcZOXsjIZmHJE/jcNfUhdsz8mXK6ftD4ZaLF14zofjPw2V6d7bnWc0nW34llx6JQvKId0wcCWwysh/XbK6cXd8HGdAkj7guaPvRp+hvVIq3WoIn4vMecoHe4Uja293p7jFNaMPYoT+SeacBSE9QqW6cPH5XPVaOjKFOLLgbohs=
      expiration: 86400000
      refresh-token:
        expiration: 60480000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Docker-specific configuration
---
spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-User:3306/user_service?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: "classpath:db/migration"
    enabled: true
    baseline-on-migrate: true
    out-of-order: true


# Local development configuration
---
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3305/user_service
#    username: root
#    password: root
