##spring.application.name=demo
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/jwt_security
#    username: root
#    password: mH@cW98#$365mySQL
#    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class
#  jpa:
#    hibernate:
#      ddl-auto: create-drop #Always start with an empty database. Destroy db when terminating the project
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL dialect
#      database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL dialect
#
##  application:
##    security:
##      jwt:
##        secret-key: QDozrk7CUofsDF1GY0NLVWY/B7lH+A9xoQ9ztn+XhRBa486xwK2ePhFxJesPVYX4UIicILdrjnH479zlt94+3TDJW7081lrfbNQYENzNq0epSHpTdtlqzntf4XONivFeRhAGslX5tnkgPOl1q3UQ5l15YNPapqg7iB6v6lySewI4BI47ncIjYcSAHl2+Rdt+wrcZOXsjIZmHJE/jcNfUhdsz8mXK6ftD4ZaLF14zofjPw2V6d7bnWc0nW34llx6JQvKId0wcCWwysh/XbK6cXd8HGdAkj7guaPvRp+hvVIq3WoIn4vMecoHe4Uja293p7jFNaMPYoT+SeacBSE9QqW6cPH5XPVaOjKFOLLgbohs=\n
##        expiration: 86400000 # a day
##        refresh-token:
##        expiration: 604800000 # 7 days
#server:
#  port: 8082
#
#  spring:
#    security:
#      oauth2:
#        client:
#          registration:
##            github:
##              clientId: Iv1.731596c579d3b990
##              clientSecret: 1a16900f622b3b74d6d2e1efa40c53a63ad8705d
#            google:
#              clientId: 937264332283-k2jkgnctiipbvqc7b566ab506kct7lp2.apps.googleusercontent.com
#              clientSecret: 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



spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: mH@cW98#$365mySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 937264332283-k2jkgnctiipbvqc7b566ab506kct7lp2.apps.googleusercontent.com
            clientSecret: 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

server:
  port: 8082


application:
  security:
    jwt:
      secret-key: QDozrk7CUofsDF1GY0NLVWY/B7lH+A9xoQ9ztn+XhRBa486xwK2ePhFxJesPVYX4UIicILdrjnH479zlt94+3TDJW7081lrfbNQYENzNq0epSHpTdtlqzntf4XONivFeRhAGslX5tnkgPOl1q3UQ5l15YNPapqg7iB6v6lySewI4BI47ncIjYcSAHl2+Rdt+wrcZOXsjIZmHJE/jcNfUhdsz8mXK6ftD4ZaLF14zofjPw2V6d7bnWc0nW34llx6JQvKId0wcCWwysh/XbK6cXd8HGdAkj7guaPvRp+hvVIq3WoIn4vMecoHe4Uja293p7jFNaMPYoT+SeacBSE9QqW6cPH5XPVaOjKFOLLgbohs=
      expiration: 86400000 # one day
      refresh-token:
        expiration: 60480000 # 7 days

