spring:
  application:
    name: discovery-service
  banner:
    location: banner.txt
  config:
    import: optional:configserver:http://config-service:8088
  profiles:
    active: docker

---
#spring:
#  application:
#    name: discovery-service
#  banner:
#      location: banner.txt
#  config:
#    import: "optional:configserver:http://config-service:8088"
