# spring.application.name=adminTask-Service
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# server.port=8090

spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: adminTask-Service
  config:
    import: "optional:configserver:http://localhost:8088"