# spring.application.name=adminTask-Service
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# server.port=8090
spring:
  application:
    name: admin-service
  banner:
    location: banner.txt
  config:
    import: optional:configserver:http://config-service:8088
    activate:
      on-profile: docker
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  application:
    name: admin-service
  config:
    import: "optional:configserver:http://localhost:8088"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  banner:
    location: banner.txt