# Common configuration for all profiles
spring:
  application:
    name: order-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/order_service?allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Docker-specific configuration
---
spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-Order:3306/order_service?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: "classpath:db/migration"
    enabled: true
    baseline-on-migrate: true
    out-of-order: true


# Local development configuration
---
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3305/order_service
#    username: root
#    password: root
