spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://localhost:8088"


#spring.application.name=order-service
#spring.datasource.url=jdbc:mysql://localhost:3306/order_service
#spring.datasource.username=root
#spring.datasource.password=992040084v
#spring.jpa.hibernate.ddl-auto=none
#server.port=8091
