# Common configuration for all profiles
spring:
  application:
    name: order-service
  banner:
    location: banner.txt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: "classpath:db/migration"
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html

# Configuration for Docker profile
---
spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://localhost:3308/order_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: "classpath:db/migration"
    enabled: true
    baseline-on-migrate: true
    out-of-order: true

# Configuration for default profile (e.g., local development)
---
#spring:
#  config:
#    import: "optional:configserver:http://localhost:8088"
#  datasource:
#    url: jdbc:mysql://localhost:3307/order_service
#    username: root
#    password: mysql
#  jpa:
#    hibernate:
#      ddl-auto: none
#  flyway:
#    enabled: true
#    baseline-on-migrate: true


