# Docker profile configuration
---
spring:
  application:
    name: learner-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker

enrollmentService:
  url: http://localhost:8060/enrollment
courseService:
  url: http://localhost:8060/course
contentService:
  url: http://localhost:8060/content

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Configuration activation for the 'docker' profile
---
spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker

# Default configuration (local development)
---
spring:
  application:
    name: learner-service
  config:
    import: "optional:configserver:http://localhost:8088"

enrollmentService:
  url: http://localhost:8060/enrollment
courseService:
  url: http://localhost:8060/course
contentService:
  url: http://localhost:8060/content
