# Common configuration for all profiles


# Configuration for the 'docker' profile
---
spring:
  application:
    name: learner-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
enrollmentService:
  url: http://enrollment-service:7010
courseService:
  url: http://course-service:7012
contentService:
  url: http://content-service:7013



springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Default configuration (e.g., for local development)
---
spring:
  config:
    import: "optional:configserver:http://localhost:8088"

enrollmentService:
  url: http://localhost:7010
courseService:
  url: http://localhost:7012
contentService:
  url: http://localhost:7013





