version: '4'
services:
  mongodb:
    image: mongo:7.0.8
    container_name: mongodb2
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: course-service
    volumes:
      - ./data:/data/db
