
# Common configuration for all profiles
spring:
  application:
    name: content-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/content_service?allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cloudinary:
  cloud_name: 
  api_key: 
  api_secret: 

# Docker-specific configuration
---
spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-Content:3306/content_service?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#  flyway:
#    locations: "classpath:db/migration"
#    enabled: true
#    baseline-on-migrate: true
#    out-of-order: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB


#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3304/content_service
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#cloudinary.cloud_name=
#cloudinary.api_key=
#cloudinary.api_secret=Cd3r9-
#
#spring.servlet.multipart.max-file-size=200MB
#spring.servlet.multipart.max-request-size=200MB
