server:
  port: 8060
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: adminTask-service
          uri: lb://adminTask-service
          predicates:
          - Path=/adminTask/**
          filters:
          - RewritePath=/adminTask/(?<path>.*), /$\{path}
        - id: content-service
          uri: lb://content-service
          predicates:
          - Path=/content/**
          filters:
          - RewritePath=/content/(?<path>.*), /$\{path}
        - id: course-service
          uri: lb://course-service
          predicates:
          - Path=/course/**
          filters:
          - RewritePath=/course/(?<path>.*), /$\{path}
        - id: email-service
          uri: lb://email-service
          predicates:
          - Path=/email/**
          filters:
          - RewritePath=/email/(?<path>.*), /$\{path}
        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
          - Path=/enrollment/**
          filters:
          - RewritePath=/enrollment/(?<path>.*), /$\{path}
        - id: learner-service
          uri: lb://learner-service
          predicates:
          - Path=/learner/**
          filters:
          - RewritePath=/learner/(?<path>.*), /$\{path}
        - id: order-service
          uri: lb://order-service
          predicates:
          - Path=/order/**
          filters:
          - RewritePath=/order/(?<path>.*), /$\{path}
        - id: payment-service
          uri: lb://payment-service
          predicates:
          - Path=/payment/**
          filters:
          - RewritePath=/payment/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

#      - id: employee-service
#        uri: lb://employee-service
#        predicates:
#        - Path=/employee/**
#        filters:
#        - RewritePath=/employee/(?<path>.*), /$\{path}
#      - id: department-service
#        uri: lb://department-service
#        predicates:
#        - Path=/department/**
#        filters:
#        - RewritePath=/department/(?<path>.*), /$\{path}
#      - id: organization-service
#        uri: lb://organization-service
#        predicates:
#        - Path=/organization/**
#        filters:
#        - RewritePath=/organization/(?<path>.*), /$\{path}

springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1

management:
  tracing:
    sampling:
      probability: 1.0