#server:
#  port: 8060
#  forward-headers-strategy: framework
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#logging:
#  pattern:
#    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
#
#spring:
#  output:
#    ansi:
#      enabled: always
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: admin-service
#          uri: lb://admin-service
#          predicates:
#          - Path=/admin/**
#          filters:
#          - RewritePath=/admin/(?<path>.*), /$\{path}
#        - id: content-service
#          uri: lb://content-service
#          predicates:
#          - Path=/content/**
#          filters:
#          - RewritePath=/content/(?<path>.*), /$\{path}
#        - id: course-service
#          uri: lb://course-service
#          predicates:
#          - Path=/course/**
#          filters:
#          - RewritePath=/course/(?<path>.*), /$\{path}
#        - id: email-service
#          uri: lb://email-service
#          predicates:
#          - Path=/email/**
#          filters:
#          - RewritePath=/email/(?<path>.*), /$\{path}
#        - id: enrollment-service
#          uri: lb://enrollment-service
#          predicates:
#          - Path=/enrollment/**
#          filters:
#          - RewritePath=/enrollment/(?<path>.*), /$\{path}
#        - id: learner-service
#          uri: lb://learner-service
#          predicates:
#          - Path=/learner/**
#          filters:
#          - RewritePath=/learner/(?<path>.*), /$\{path}
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#          - Path=/order/**
#          filters:
#          - RewritePath=/order/(?<path>.*), /$\{path}
#        - id: payment-service
#          uri: lb://payment-service
#          predicates:
#          - Path=/payment/**
#          filters:
#          - RewritePath=/payment/(?<path>.*), /$\{path}
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user/**
#          filters:
#            - RewritePath=/user/(?<path>.*), /$\{path}
#        - id: openapi
#          uri: http://localhost:${server.port}
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
#
#springdoc:
#  cache:
#    disabled: true
#  version: '@springdoc.version@'
#  swagger-ui:
#    use-root-path: true
#  api-docs:
#    version: openapi_3_1
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0