# Default configuration (used for local development)
spring:
  application:
    name: email-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://localhost:8088"
  mail:
    host: smtp.gmail.com
    username: 
    password: 
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html

# Docker profile configuration
---
spring:
  application:
    name: email-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
  mail:
    host: smtp.gmail.com
    username: 
    password: 
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

