spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: email-service
  config:
    import: "optional:configserver:http://localhost:8088"
  mail:
    host: smtp.gmail.com
    username: hansaniwork1@gmail.com
    password: sfjm ylep nbll qvig
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


##spring.application.name=email
#spring:
#  mail:
#    host: smtp.gmail.com
#    username: hansaniwork1@gmail.com
#    password: sfjm ylep nbll qvig
#    port: 587
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true
#
#server:
#  port: 8081
#
#
